src/evemu.c: fix build with kernels >= 4.16
Commit 30973c0b forgot to update all occurences of input_event, this
will result in the following build failure with kernel >= 4.16:

evemu.c: In function 'write_event_desc':
evemu.c:753:23: error: 'const struct input_event' has no member named 'time'; did you mean 'type'?
    time = millis(&ev->time);
                       ^~~~
                       type

Fixes:
 - http://autobuild.buildroot.org/results/487dd5056ec0a977d55b23417d5db2664dcc91fa

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>