src/evemu.c: fix build with kernels < 4.16
Commit 30973c0b fixed the build with kernels >= 4.16 but as a side
effect, build with kernels < 4.16 is now failing on:

evemu.c:892:18: error: ‘struct input_event’ has no member named ‘input_event_usec’
   tv.tv_usec = ev->input_event_usec;
                  ^~

Fix this error by defining input_event_sec and input_event_usec if
needed

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>